### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by JellyKid** [konstantin-kelemen/arduino-amiibo-tools-pn532#1]
This project is a great resource, I wanted to say thanks for putting it out there. I'm writing my own node.js based tool that integrates everything together(If I would have seen [Wifiibo](https://github.com/Xerxes3rd/Wifiibo) first I probably wouldn't have started my own, but anyways).  

I just have a question about the PN532 library that I'm hoping you could answer. The module I'm using is the NFC V3 from elechouse on Firmware V1.6. I've successfully written a few tags with your tool, but I'm running into an issue that I'm not sure if the problem is the module or the library. **When writing a tag, if you remove the tag from the module part way through it keeps going through the writing process and never actually fails.** Any chance you confirm this behavior as well?

**Comment by konstantin-kelemen** [comment]
Hi @JellyKid, thanks for your interest in my project!

Yes, as I have [mentioned in my blog](https://games.kel.mn/en/create-amiibo-clones-with-arduino-and-pn532-nfc-module/), this is a know issue that the checking procedure simply doesn’t work as intended, always reporting success.

[Xerxes3rd](https://github.com/Xerxes3rd), the author of [Wifiibo](https://github.com/Xerxes3rd/Wifiibo), has implemented several fixes into the Adafruit PN523 library, making it faster and more stable, you can try it and see, if that issue has been fixed there.
